#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

#define ASSIGN_OP 10
#define LESSER_OP 11
#define GREATER_OP 12
#define EQUAL_OP 13
#define NEQUAL_OP 14
#define LEQUAL_OP 15
#define GEQUAL_OP 16
#define OPEN_PAREN 17
#define CLOSE_PAREN 18
#define ADD_OP 19
#define SUB_OP 20
#define MULT_OP 21
#define DIV_OP 22
#define MOD_OP 23
#define BOOL_AND 24
#define BOOL_OR 25
#define BOOL_NOT 26
#define SEMICOLON 27
#define KEY_IN 28
#define KEY_OUT 29
#define KEY_IF 30
#define KEY_ELSE 31
#define OPEN_CURL 32
#define CLOSE_CURL 33
#define IDENT 34
#define INT_LIT 35

